<a href="https://colab.research.google.com/github/Hanifanta/Capstone_RECCOFFEE/blob/main/Reccofee_Test2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q kaggle

from google.colab import files
files.upload()

Saving kaggle (1).json to kaggle (1).json


{'kaggle (1).json': b'{"username":"hanifalirsyad","key":"28c0e24be20292ec34a8d71654452d0a"}'}

In [5]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

In [6]:
!chmod 600 /root/.kaggle/kaggle.json

In [8]:
!kaggle datasets download -d hanifalirsyad/coffee-scrap-coffeereview

 67% 1.00M/1.50M [00:00<00:00, 1.99MB/s]
100% 1.50M/1.50M [00:00<00:00, 2.72MB/s]


In [9]:
!unzip /content/coffee-scrap-coffeereview.zip

Archive:  /content/coffee-scrap-coffeereview.zip
  inflating: coffee_df_test.csv      
  inflating: coffee_fix.csv          
  inflating: slug1.csv               


In [11]:
import pandas as pd
df = pd.read_csv('/content/coffee_fix.csv')
df.head()

slug  \
0  https://www.coffeereview.com/review/sweety-esp...   
1  https://www.coffeereview.com/review/flora-blen...   
2  https://www.coffeereview.com/review/ethiopia-s...   
3  https://www.coffeereview.com/review/ethiopia-s...   
4  https://www.coffeereview.com/review/ethiopia-g...   

                                            all_text  rating  \
0   \n\n\n95\n\n\nA.R.C.\n“Sweety” Espresso Blend...      95   
1   \n\n\n94\n\n\nA.R.C.\nFlora Blend Espresso\n\...      94   
2   \n\n\n92\n\n\nRevel Coffee\nEthiopia Shakiso ...      92   
3   \n\n\n92\n\n\nRoast House\nEthiopia Suke Quto...      92   
4   \n\n\n94\n\n\nBig Creek Coffee Roasters\nEthi...      94   

                     roaster                        name             location  \
0                     A.R.C.     “Sweety” Espresso Blend     Hong Kong, China   
1                     A.R.C.        Flora Blend Espresso     Hong Kong, China   
2               Revel Coffee    Ethiopia Shakiso Mormora    Billings, Montana   
3                Roast House          Ethiopia Suke Quto  Spokane, Washington   
4  Big Creek Coffee Roasters  Ethiopia Gedeb Halo Beriti    Hamilton, Montana   

                                             origin         roast  \
0                                  Panama; Ethiopia  Medium-Light   
1                              Africa; Asia Pacific  Medium-Light   
2                      Guji Zone, southern Ethiopia  Medium-Light   
3  Guji Zone, Oromia Region, south-central Ethiopia  Medium-Light   
4     Gedeb District, Gedeo Zone, southern Ethiopia        Medium   

            est_price    review_date agtron  aroma  acid  body  flavor  \
0  HKD $250/227 grams  November 2017  50/73    9.0   NaN   9.0     9.0   
1  HKD $158/227 grams  November 2017  54/77    9.0   NaN   9.0     9.0   
2    $16.00/12 ounces  November 2017  54/70    9.0   8.0   8.0     9.0   
3    $19.00/16 ounces  November 2017  53/79    8.0   8.0   9.0     9.0   
4    $16.50/12 ounces  November 2017  48/70    9.0   9.0   9.0     9.0   

   aftertaste  with_milk                                             desc_1  \
0         9.0        9.0  Evaluated as espresso. Sweet-toned, deeply ric...   
1         8.0        9.0  Evaluated as espresso. Sweetly tart, floral-to...   
2         8.0        NaN  Crisply sweet, cocoa-toned. Lemon blossom, roa...   
3         8.0        NaN  Delicate, sweetly spice-toned. Pink peppercorn...   
4         8.0        NaN  Deeply sweet, subtly pungent. Honey, pear, tan...   

                                              desc_2  \
0  An espresso blend comprised of coffees from Pa...   
1  An espresso blend comprised of coffees from Af...   
2  This coffee tied for the third-highest rating ...   
3  This coffee tied for the third-highest rating ...   
4  Southern Ethiopia coffees like this one are pr...   

                                              desc_3  
0  A radiant espresso blend that shines equally i...  
1  A floral-driven straight shot, amplified with ...  
2  A gently spice-toned, floral- driven wet-proce...  
3  Lavender-like flowers and hints of zesty pink ...  
4  A deeply and generously lush cup saved from se...

In [19]:
values = {'roast': 'Unknown', 'aroma': 0.0, 'acid': 0.0, 'body': 0.0, 'flavor': 0.0, 'aftertaste': 0.0}
df.fillna(values, inplace=True)
df

slug  \
0     https://www.coffeereview.com/review/sweety-esp...   
1     https://www.coffeereview.com/review/flora-blen...   
2     https://www.coffeereview.com/review/ethiopia-s...   
3     https://www.coffeereview.com/review/ethiopia-s...   
4     https://www.coffeereview.com/review/ethiopia-g...   
...                                                 ...   
2277  https://www.coffeereview.com/review/finca-patz...   
2278  https://www.coffeereview.com/review/proyecto-a...   
2279  https://www.coffeereview.com/review/finca-el-p...   
2280  https://www.coffeereview.com/review/chacaya-sa...   
2281  https://www.coffeereview.com/review/espresso-n...   

                                               all_text  rating  \
0      \n\n\n95\n\n\nA.R.C.\n“Sweety” Espresso Blend...      95   
1      \n\n\n94\n\n\nA.R.C.\nFlora Blend Espresso\n\...      94   
2      \n\n\n92\n\n\nRevel Coffee\nEthiopia Shakiso ...      92   
3      \n\n\n92\n\n\nRoast House\nEthiopia Suke Quto...      92   
4      \n\n\n94\n\n\nBig Creek Coffee Roasters\nEthi...      94   
...                                                 ...     ...   
2277   \n\n\n92\n\n\nEl Gran Cafe\nFinca Patzibir\n\...      92   
2278   \n\n\n93\n\n\nEl Gran Cafe\nProyecto Aurora\n...      93   
2279   \n\n\n93\n\n\nEl Gran Cafe\nFinca El Potrero\...      93   
2280   \n\n\n93\n\n\nEl Gran Cafe\nChacayá Santiago ...      93   
2281   \n\n\n94\n\n\nEl Gran Cafe\nEspresso No. 3\n\...      94   

                        roaster                        name  \
0                        A.R.C.     “Sweety” Espresso Blend   
1                        A.R.C.        Flora Blend Espresso   
2                  Revel Coffee    Ethiopia Shakiso Mormora   
3                   Roast House          Ethiopia Suke Quto   
4     Big Creek Coffee Roasters  Ethiopia Gedeb Halo Beriti   
...                         ...                         ...   
2277               El Gran Cafe              Finca Patzibir   
2278               El Gran Cafe             Proyecto Aurora   
2279               El Gran Cafe            Finca El Potrero   
2280               El Gran Cafe    Chacayá Santiago Atitlán   
2281               El Gran Cafe              Espresso No. 3   

                 location                                            origin  \
0        Hong Kong, China                                  Panama; Ethiopia   
1        Hong Kong, China                              Africa; Asia Pacific   
2       Billings, Montana                      Guji Zone, southern Ethiopia   
3     Spokane, Washington  Guji Zone, Oromia Region, south-central Ethiopia   
4       Hamilton, Montana     Gedeb District, Gedeo Zone, southern Ethiopia   
...                   ...                                               ...   
2277   Antigua, Guatemala            Lake Atitlán growing region, Guatemala   
2278   Antigua, Guatemala                 Antigua growing region, Guatemala   
2279   Antigua, Guatemala                 Antigua growing region, Guatemala   
2280   Antigua, Guatemala            Lake Atitlán growing region, Guatemala   
2281   Antigua, Guatemala                 Antigua growing region, Guatemala   

             roast           est_price    review_date agtron  aroma  acid  \
0     Medium-Light  HKD $250/227 grams  November 2017  50/73    9.0   0.0   
1     Medium-Light  HKD $158/227 grams  November 2017  54/77    9.0   0.0   
2     Medium-Light    $16.00/12 ounces  November 2017  54/70    9.0   8.0   
3     Medium-Light    $19.00/16 ounces  November 2017  53/79    8.0   8.0   
4           Medium    $16.50/12 ounces  November 2017  48/70    9.0   9.0   
...            ...                 ...            ...    ...    ...   ...   
2277  Medium-Light    $16.00/12 ounces  November 2022  56/74    8.0   8.0   
2278  Medium-Light    $10.00/12 ounces  November 2022  58/76    9.0   9.0   
2279  Medium-Light    $10.00/12 ounces  November 2022  60/76    9.0   9.0   
2280  Medium-Light    $16.00/12 ounces  November 2022  55/73 

In [38]:
data = df.filter(['name','aroma','acid','body'])
data

name  aroma  acid  body
0        “Sweety” Espresso Blend    9.0   0.0   9.0
1           Flora Blend Espresso    9.0   0.0   9.0
2       Ethiopia Shakiso Mormora    9.0   8.0   8.0
3             Ethiopia Suke Quto    8.0   8.0   9.0
4     Ethiopia Gedeb Halo Beriti    9.0   9.0   9.0
...                          ...    ...   ...   ...
2277              Finca Patzibir    8.0   8.0   9.0
2278             Proyecto Aurora    9.0   9.0   8.0
2279            Finca El Potrero    9.0   9.0   8.0
2280    Chacayá Santiago Atitlán    9.0   8.0   8.0
2281              Espresso No. 3    9.0   0.0   9.0

[2282 rows x 4 columns]

In [77]:
X = data.loc[:, data.columns != 'name'].values
y = data['name']
y.head()

0       “Sweety” Espresso Blend
1          Flora Blend Espresso
2      Ethiopia Shakiso Mormora
3            Ethiopia Suke Quto
4    Ethiopia Gedeb Halo Beriti
Name: name, dtype: object

In [71]:
# X = data.iloc[:, 0:-1]
# y = data.iloc[:, -1]

In [78]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25)

In [74]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

In [79]:
model.fit(X, y)

RandomForestClassifier()

In [80]:
model.score(X,y)

0.02716914986853637

In [81]:
predictions = model.predict(X)
predictions[:500]

array(['Flight Seasonal Espresso', 'Flight Seasonal Espresso',
       'House Blend', '100% Organic Specialty Arabica', 'Kona Mocca®',
       'Ethiopia Kayon Mountain', 'Ethiopia Kayon Mountain',
       'Ethiopia Kayon Mountain', 'Monte Alban Mexico', 'Kona Mocca®',
       'Kona Mocca®', 'Ethiopia Kayon Mountain', 'Espresso Blend',
       'Augie’s Ethiopia Layo Teraga Washed (Instant Coffee)', 'Espresso',
       'Espresso', '“Nutty” Espresso Blend',
       '100% Organic Specialty Arabica', 'House Blend', 'Espresso Blend',
       'House Blend', 'Flight Seasonal Espresso', 'Sumatra Dark',
       'Ethiopia Kayon Mountain', 'Sumatra Dark',
       'Elida Estate Dragonfly Catuai Lot 13', 'Kona Mocca®',
       'House Blend', 'Kona Mocca®', 'Espresso Blend',
       'Flight Seasonal Espresso', 'Kona Mocca®', 'House Blend',
       '100% Organic Specialty Arabica', 'Colombia', 'Sítio Pedra Menina',
       'Colombia Finca El Paraiso Double Anaerobic Geisha',
       'Thanksgiving Blend', 'Thanksgivi

In [82]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y, predictions))
print(confusion_matrix(y, predictions))
print(classification_report(y, predictions))

0.02716914986853637
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]
                                                                       precision    recall  f1-score   support

                                                          #She_Builds       0.00      0.00      0.00         1
                 100% Arabica Freeze-Dried Colombian (Instant Coffee)       0.00      0.00      0.00         1
                                                      100% Guatemalan       0.00      0.00      0.00         1
                                                    100% Kona Bourbon       0.00      0.00      0.00         1
                                     100% Kona Bourbon Pointu Laurina       0.00      0.00      0.00         4
                                                      100% Kona SL-28       0.00      0.00      0.00         1
                                       100% Organic Specialty Arabica       0.01  

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [83]:
import joblib

joblib.dump(model,'/content/randomforest_model.pkl')

['/content/randomforest_model.pkl']

In [96]:
import numpy as np
test_data = [9.0, 9.0, 9.0]

test_data = np.array(test_data)

test_data = test_data.reshape(1,-1)
print(test_data)

[[9. 9. 9.]]


In [85]:
filePath = '/content/randomforest_model.pkl'

file = open(filePath, "rb")

trained_model = joblib.load(file)

In [97]:
prediction = trained_model.predict(test_data)
print(prediction)

['Kona Mocca®']


In [98]:
data[data['name'] == 'Kona Mocca®']

name  aroma  acid  body
140   Kona Mocca®    9.0   9.0   9.0
401   Kona Mocca®    9.0   9.0   9.0
1160  Kona Mocca®   10.0   9.0   9.0
1372  Kona Mocca®    9.0   9.0   9.0
1724  Kona Mocca®    9.0   9.0   9.0